In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.model_selection import train_test_split,RandomizedSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, roc_auc_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn import metrics

import matplotlib.pyplot as plt
%matplotlib inline



In [2]:
df_2 = pd.read_csv(r'C:\Users\aryan\Downloads\data\df.csv')

In [3]:
df_2.head()

Unnamed: 0  Months_loan_taken_for  Principal_loan_amount  \
0           0                      6                1169000   
1           1                     48                5951000   
2           2                     12                2096000   
3           3                     42                7882000   
4           4                     24                4870000   

   EMI_rate_in_percentage_of_disposable_income  \
0                                            4   
1                                            2   
2                                            2   
3                                            2   
4                                            3   

   Number_of_existing_loans_at_this_bank  high_risk_applicant  \
0                                      2                    0   
1                                      1                    1   
2                                      1                    0   
3                                      1                    0   
4                                      2                    1   

   Primary_applicant_age_in_years  Number_of_dependents  \
0                              67                     1   
1                              22                     1   
2                              49                     2   
3                              45                     2   
4                              53                     2   

   Years_at_current_residence  \
0                           4   
1                           2   
2                           3   
3                           4   
4                           4   

   Balance_in_existing_bank_account_(lower_limit_of_bucket)  ...  \
0                                                  0         ...   
1                                                  0         ...   
2                                                  0         ...   
3                                                  0         ...   
4                                                  0         ...   

   Savings_account_balance_Very high  \
0                                  0   
1                                  0   
2                                  0   
3                                  0   
4                                  0   

   Loan_history_all loans at this bank paid back duly.1  \
0                                                  0      
1                                                  0      
2                                                  0      
3                                                  0      
4                                                  0      

   Loan_history_critical/pending loans at other banks.1  \
0                                                  1      
1                                                  0      
2                                                  1      
3                                                  0      
4                                                  0      

   Loan_history_delay in paying off loans in the past.1  \
0                                                  0      
1                                                  0      
2                                                  0      
3                                                  0      
4                                                  1      

   Loan_history_existing loans paid back duly till now.1  \
0                                                  0       
1                                                  1       
2                                                  0       
3                                                  1       
4                                                  0       

   Loan_history_no loans taken/all loans paid back duly.1  \
0                                                  0        
1                                                  0        
2                                                  0        
3                                                  0      

column_header = list(df_2.columns)
column_header

### Now all columns are numeric, we fit a Standard Scaler to normalize the numeric variables

In [4]:
standardScaler = StandardScaler()
columns_to_scale = ['Principal_loan_amount','Months_loan_taken_for',
                   'EMI_rate_in_percentage_of_disposable_income',
                   'Primary_applicant_age_in_years',
                    'Number_of_dependents',
                    'Years_at_current_residence']
df_2[columns_to_scale]= standardScaler.fit_transform(df_2[columns_to_scale])

In [5]:
column_headers = list(df_2.columns.values)
column_headers

['Unnamed: 0',
 'Months_loan_taken_for',
 'Principal_loan_amount',
 'EMI_rate_in_percentage_of_disposable_income',
 'Number_of_existing_loans_at_this_bank',
 'high_risk_applicant',
 'Primary_applicant_age_in_years',
 'Number_of_dependents',
 'Years_at_current_residence',
 'Balance_in_existing_bank_account_(lower_limit_of_bucket)',
 'Balance_in_existing_bank_account_(upper_limit_of_bucket)',
 'Gender_female',
 'Gender_male',
 'Purpose_FF&E',
 'Purpose_business',
 'Purpose_career development',
 'Purpose_domestic appliances',
 'Purpose_education',
 'Purpose_electronic equipment',
 'Purpose_new vehicle',
 'Purpose_repair costs',
 'Purpose_used vehicle',
 'Marital_status_divorced/separated',
 'Marital_status_divorced/separated/married',
 'Marital_status_married/widowed',
 'Marital_status_single',
 'Property_building society savings agreement/life insurance',
 'Property_car or other',
 'Property_real estate',
 'Loan_history_all loans at this bank paid back duly',
 'Loan_history_critical/pend

#### Using train_test_split function from sklearn and a split ratio of 80:20

In [6]:
y = df_2['high_risk_applicant']
X = df_2.drop(['high_risk_applicant','Unnamed: 0'], axis = 1)
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 0)

param_grid = {
    'max_depth': range(4,25),
    'min_sample_leaf' : range(10,100,10),
    'min_sample_split': range(10,100,10),
    'criterion' : ['gini', 'entropy']    
}
n_folds = 5

dt = DecisionTreeClassifier(random_state =np.random.randint(0,100))
dt_grid = GridSearchCV(df,param_grid,cv = n_folds,return_train_score=True,verbose=0)
dt_grid.fit(X_train,y_train)
print(dt_grid.best_params_)

y_pred_best=dt_grid.predict(X_train)\
acc = metrics.accuracy_score(y_test,y_pred_best)
print(acc)

r_param_grid = {
   'n_estimators' : rangee(1,1000,100),
}
 r = RandomForestClassifier()
    
 r_random = RandomizedSearchCV(param_distributions=rf_param_grid,
                                estimator = rf,scoring = "accuracy",
                                verbose = 0, n_iter = 100, cv =4)

rf_random.fit(X_train,y_train)
best_params = rf_random.best_params_
print(f'best parameters: {best_params}')

y_pred1 = rf_random.predict(X_test)
print(f'Accuracy: {np.sum(y_pred1==y_test)/len(y_test)}')
                                 
    


In [7]:
DTClassifier= DecisionTreeClassifier(criterion = 'entropy', random_state=42)
DTClassifier.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [8]:
y_pred =DTClassifier.predict(X_test)
y_pred

array([1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0], dtype=int64)

###  Accuracy along the confusion matrix of DecisionTreeClassifier

In [9]:
print('The accuracy is ',metrics.accuracy_score(y_pred,y_test))

The accuracy is  0.64


In [11]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred,y_test)


array([[108,  38],
       [ 34,  20]], dtype=int64)

In [12]:
from sklearn.naive_bayes import GaussianNB
NBClassifier = GaussianNB()
NBClassifier.fit(X_train,y_train)

GaussianNB()

In [13]:
y_pred= NBClassifier.predict(X_test)
y_pred

array([0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0], dtype=int64)

###  Accuracy along the confusion matrix of Gaussian Naive Bayes  (probabilistic classification algorithm)  

In [14]:
print('THe accuracy',metrics.accuracy_score(y_pred,y_test))

THe accuracy 0.695


In [15]:


confusion_matrix(y_pred,y_test)

array([[116,  35],
       [ 26,  23]], dtype=int64)